### ISSUE TITLE
Amazing!

### ISSUE THREAD

**Issue by cnarutox** [cryham/sph-cuda#1]
Hello! What you made is really amazing!
But maybe it was finished by the CUDA version before 5.0, so I can't compile it successfully without cutil.h(CUDA 5 and later versions remove the cutil.h). After several days' hard process, I managed to load cutil.h but there appeared more questions of lib(cutil32.lib, tinyxml_STL.lib......). If possible, I hope you may transplant the project to CUDA 9.1 and VS2015. I will appreciate it very much!

**Comment by cryham** [comment]
Hi. Sorry, won't do. I didn't do anything with CUDA in nearly 10 years.

**Comment by sitonmoon** [comment]
@cnarutox I compiled this project successful , and I am doing work to restructure code in cuda 6.5.  Maybe it will take sevral days.  Thanks cryham a lot.
