### ISSUE TITLE
has problem with cuda6.5

### ISSUE THREAD

**Issue by sitonmoon** [cryham/sph-cuda#2]
I am interesting in this project ,  but i have some problem with the code :
First , I don't know which version of CUDA you use,so I use CUDA 6.5 version. 
Then there is some link error when I use CUDA 6.5 to compile the program , but I fixed all problem and complied successfully.
The key is there is no reason when I run the EXE ? I am confuse. Hope to give me some help.

**Comment by cryham** [comment]
No idea. Was from 2009. I didn't touch this project for 9 years.
